import Dexie, { type Table } from 'dexie';
import { AnalysisResult } from '../types';

/**
 * DeepShield Vault Storage Engine
 * Persistent IndexedDB layer for high-fidelity forensic data.
 */
export class DeepShieldDatabase extends Dexie {
  reports!: Table<AnalysisResult & { thumbnail?: string }>;

  constructor() {
    super('deepshield_db');
    this.version(1).stores({
      // Using 'id' directly as the forensic ID is a unique string generated by the service
      reports: 'id, timestamp, fileName, classification, fileHash'
    });
  }
}

export const db = new DeepShieldDatabase();

export const dbService = {
  async saveReport(result: AnalysisResult, thumbnail?: string): Promise<string> {
    try {
      return await db.transaction('rw', db.reports, async () => {
        return await db.reports.add({ ...result, thumbnail });
      });
    } catch (err) {
      console.error("Vault injection failed:", err);
      throw new Error("Unable to commit forensic report to the secure vault.");
    }
  },

  async getAllReports(): Promise<AnalysisResult[]> {
    return await db.reports.orderBy('timestamp').reverse().toArray();
  },

  async getReportCount(): Promise<number> {
    return await db.reports.count();
  },

  async deleteReport(id: string): Promise<void> {
    return await db.reports.delete(id);
  },

  async purgeDatabase(): Promise<void> {
    return await db.reports.clear();
  },

  async getDatabaseSize(): Promise<{ usage: number; quota: number }> {
    if ('storage' in navigator && 'estimate' in navigator.storage) {
      try {
        const estimate = await navigator.storage.estimate();
        return {
          usage: estimate.usage || 0,
          quota: estimate.quota || 0
        };
      } catch {
        return { usage: 0, quota: 0 };
      }
    }
    return { usage: 0, quota: 0 };
  }
};